bugfixes: exclude nan in sqlite
**Error Description**

Program exits throwing error of SQLite operations.
```text
Error using saveLiConst (line 62)
Java exception occurred:
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no
such column: NaN)
at org.sqlite.core.DB.newSQLException(DB.java:941)
at org.sqlite.core.DB.newSQLException(DB.java:953)
at org.sqlite.core.DB.throwex(DB.java:918)
at org.sqlite.core.NativeDB._exec_utf8(Native Method)
at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
at
org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)

Error in picassoProcV3 (line 4389)
saveLiConst(dbFile, LC.LC_raman_355, LC.LCStd_raman_355, ...
```

**Error Analysis**

When the lidar calibration constants were very wrong or not stable in any region, the uncertainty of lidar calibration constant will be `NaN`, while lidar calibration constant could still be a `double` value. This will trigger error of SQLite INSERT when trying to put `NaN` value into a table with data type of `REAL`.

**Solution**

Add an addition conditional check for the uncertainty of lidar calibration constant. Also implemented similar check for water vapor calibration constant and polarization calibration constant.

close #169