Dev to master (#185)
* Docs: Update docstring

Improve matlab function docstrings.

* Update getPicassoVersion.m

for dev branch

* Added case 3 to read sounding data from Mosaic

* proposal for new standard config

* bugfixes? added disp(mwrResFileSearch); to lib/io/readIWV.m

* bug fix

minor bug fixes

* Update polly_global_config.json

Proposal for a new global config

* Bugfixes: use manual ref H

Correct the logic for using manual reference height.

Associated with issue #87.

* Bugfixes: correct Raman channel for nr

Correct the near-range Raman channel index for near-range Raman retrieval.

Close issue #160

* Save lc nf (#167)

* added plotting of near range NF

* Update pollyDisplayLC.m

near range calibration only avaliable for Raman

* updates for plotting

* updated long term cali plotting

For CV only, needs to be cleaned up and restructured in future

* recommendation after pull requesr review

* bug fix before merge

* refractor: toolbox check

Check whether required Matlab toolboxes were activated for running Picasso.

* Enhancement: update sqlite driver

Replace SQLite driver with JDBC instead of Matlab database toolbox.

Associated with #169

* Enhancement: speed-up extract_cali_results

* compare timestamps of filename with timestamps from within nc-file (#173)

* mTime values will be readout from within nc-file (seconds of day), not from filename

* mTime will be read from within nc-file if date is not 19700101, otherwise mTime will be taken from filename

* measurementtime from within nc-file will be compared with timestamp of nc-filename

* bugfixes: sqlite read error

Bug report:

Program exits and throws SQLite error.

Bug analysis:

No `rs` instance was initialized when accessing a table which does not exist in SQLite database. This will trigger error when closing `rs` instance.

Bug fixes:

Do not close `rs` instance when it does not exist.

Close issue #174

* Check if gdas1 height values are linear rising, refers to issue 176 in github (#177)

* bugfixes: exclude nan in sqlite

**Error Description**

Program exits throwing error of SQLite operations.
```text
Error using saveLiConst (line 62)
Java exception occurred:
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no
such column: NaN)
at org.sqlite.core.DB.newSQLException(DB.java:941)
at org.sqlite.core.DB.newSQLException(DB.java:953)
at org.sqlite.core.DB.throwex(DB.java:918)
at org.sqlite.core.NativeDB._exec_utf8(Native Method)
at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
at
org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)

Error in picassoProcV3 (line 4389)
saveLiConst(dbFile, LC.LC_raman_355, LC.LCStd_raman_355, ...
```

**Error Analysis**

When the lidar calibration constants were very wrong or not stable in any region, the uncertainty of lidar calibration constant will be `NaN`, while lidar calibration constant could still be a `double` value. This will trigger error of SQLite INSERT when trying to put `NaN` value into a table with data type of `REAL`.

**Solution**

Add an addition conditional check for the uncertainty of lidar calibration constant. Also implemented similar check for water vapor calibration constant and polarization calibration constant.

close #169

* bug fixed, long term cali was not stored yet

* further tuning for bug fixed, long term cali was not stored yet

* added SNR to WV output

there was a need to add the SNR at 387 and 407 to the netcdf. Furthermore the calibration constant + uncertainty was stored.

Co-authored-by: Zhenping <zp.yin@whu.edu.cn>
Co-authored-by: Cristofer Jimenez <jimenez@tropos.de>
Co-authored-by: Baymax <test@email.com>
Co-authored-by: ulysses78 <86650998+ulysses78@users.noreply.github.com>